[project]
name = "swjtu-course-selection-script"
version = "1.1.0"
description = "西南交通大学选课脚本"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddddocr>=1.5.6",
    "lxml>=6.0.2",
    "marimo>=0.18.4",
    "requests>=2.32.5",
]
